gText_Birch_Welcome::
	.string "Welcome, young DRAGON TAMER!\p"
    .string "In this village, we raise DRAGONs\n"
    .string "with care and dedication.\p"
    .string "Each DRAGON is a symbol of our\n"
    .string "strength and wisdom.$"

gText_Birch_Pokemon::
	.string "Today marks the beginning of your\n"
    .string "coming of age ritual.\p"
    .string "You will embark on a journey to\n"
    .string "prove your worth as a true DRAGON TAMER.$"

gText_Birch_MainSpeech::
	.string "Your task is to bond with a DRATINI\n"
    .string "and demonstrate your mastery.\p"
    .string "Only then will you earn the title\n"
    .string "of a true DRAGON TAMER.$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Which of these appearances suites you?\n"
	.string "best?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who lives in their\n"
	.string "hometown of DRAGON VILLAGE.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!$"
